name: react-edge-personalization
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      working-directory: ./examples/react-edge-personalization/remote
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "12"
      - run: yarn
        working-directory: ${{ env.working-directory }}

      - run: yarn build:lambda
        working-directory: ${{ env.working-directory }}

      - name: Federated Container Action
        id: container
        uses: jacob-ebey/federated-container-action@0.0.0-beta.1
        with:
          config: "${{ env.working-directory }}/webpack.config.js"
          exposes: "${{ env.working-directory }}/exposes.js"
          shared: "${{ env.working-directory }}/shared.js"

      - run: ls -lh ${{ steps.container.outputs.path0 }}
      - run: ls -lh ${{ steps.container.outputs.path1 }}

      # - name: Vercel Deployment
      #   uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-args: "--prod"
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      #     vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
      #     working-directory: ${{ env.working-directory }}
